### ISSUE TITLE
Rest Test Failure on v0.2.6 (Tomcat deploy failure)

### ISSUE THREAD

**Issue by Diom** [cchacin/cucumber-common-steps#16]
Hi Carlos,

I've forked your project with the hope of being able to contribute. I have managed to compile etc... once I figured out the Lombok requirements, however the tests are not passing for me and unfortunately the errors are not entirely helpful.

I run `mv clean install` and the test in error is `RestfulSuccessTest.com.github.cchacin.cucumber.steps.rest.RestfulSuccessTest » Deployment`.
The core of the issue appears to be in the Arquillian auto-deploy of the embedded Tomcat server, but there is not much info given:
```console
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.028 sec <<< FAILURE! - in com.github.cchacin.cucumber.steps.rest.RestfulSuccessTest
com.github.cchacin.cucumber.steps.rest.RestfulSuccessTest  Time elapsed: 7.027 sec  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Unable to deploy
...
Caused by: org.apache.openejb.OpenEJBRuntimeException: java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[/test-app]]
...
Caused by: java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[/test-app]]
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
at org.apache.tomee.catalina.TomcatWebAppBuilder.deployWar(TomcatWebAppBuilder.java:648)
at org.apache.tomee.catalina.TomcatWebAppBuilder.deployWebApps(TomcatWebAppBuilder.java:618)
at org.apache.tomee.catalina.deployment.TomcatWebappDeployer.deploy(TomcatWebappDeployer.java:43)
... 90 more
```
**What I have tried**
I am only barely familiar with Arquillian so I've only tried to modify the deployment port in `arquillian.xml`
```xml
    <container qualifier="tomee" default="true">
        <configuration>
            <property name="httpPort">8082</property>
            <property name="stopPort">-1</property>
        </configuration>
    </container>
```
Which made no difference.
Am I missing a build setup step?

**Comment by cchacin** [comment]
@Diom this is my environment:

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

And the command is: mvn clean install

Do you have a local tomcat running in the 8080 port?

**Comment by cchacin** [comment]
@Diom can you check with the latest version? -> 0.2.10

**Comment by Diom** [comment]
@cchacin I haven't a tomcat instance running. I was under the impression that it is deployed by Arquillian? I recently changed by dev machine so it'll be a while before I get a chance to check this out again.

**Comment by cchacin** [comment]
Ok I'll to close this and feel free to create an issue when you return to this.
