### ISSUE TITLE
 java.sql.SQLException: No suitable driver found 

### ISSUE THREAD

**Issue by anujacharya1** [cchacin/cucumber-common-steps#19]
Getting the following issue when trying to use hsqldb. In my pom I have the dependency.

```com.ninja_squad.dbsetup.DbSetupRuntimeException: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:mem:test
at com.ninja_squad.dbsetup.DbSetup.launch(DbSetup.java:123)
  at com.github.cchacin.cucumber.steps.DatabaseSteps.apply(DatabaseSteps.java:100)
  at com.github.cchacin.cucumber.steps.DatabaseSteps.deleteAll(DatabaseSteps.java:96)
  at com.github.cchacin.cucumber.steps.DatabaseSteps.I_have_only_the_following_rows_in_the_table(DatabaseSteps.java:74)
  at ✽.Given I have only the following rows in the "offer_contexts" table:(/Users/anuj.acharya/IdeaProjects/cucumber-regression/src/test/resources/features/Some/Some.feature:8)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:mem:test
  at java.sql.DriverManager.getConnection(DriverManager.java:596)
  at java.sql.DriverManager.getConnection(DriverManager.java:215)
  at com.ninja_squad.dbsetup.destination.DriverManagerDestination.getConnection(DriverManagerDestination.java:89)
  at com.ninja_squad.dbsetup.DbSetup.launch(DbSetup.java:104)
  at com.github.cchacin.cucumber.steps.DatabaseSteps.apply(DatabaseSteps.java:100)
  at com.github.cchacin.cucumber.steps.DatabaseSteps.deleteAll(DatabaseSteps.java:96)
  at com.github.cchacin.cucumber.steps.DatabaseSteps.I_have_only_the_following_rows_in_the_table(DatabaseSteps.java:74)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at cucumber.runtime.Utils$1.call(Utils.java:34)
  at cucumber.runtime.Timeout.timeout(Timeout.java:13)
  at cucumber.runtime.Utils.invoke(Utils.java:30)
  at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:35)
  at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
  at cucumber.runtime.Runtime.runStep(Runtime.java:298)
  at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
  at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
  at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:48)
  at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:154)
  at cucumber.runtime.Runtime.run(Runtime.java:120)
  at cucumber.runtime.Runtime.run(Runtime.java:108)
  at cucumber.api.cli.Main.run(Main.java:36)
  at cucumber.api.cli.Main.main(Main.java:18)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)```

**Comment by cchacin** [comment]
@anujacharya1 Do you have the ```src/test/resource/test-db.properties``` file specifying the driver?

like:
```properties
database.url=jdbc:hsqldb:mem:test
database.driver=org.hsqldb.jdbc.JDBCDriver
database.user=SA
database.password=
```
